export const SLA_INDUSTRIES = ['Security','Audio/Visual','IT / Networking','Low Voltage','Fire Protection','HVAC','Electrical','Telecom','Solar','Mechanical','Plumbing','General Contractor','Other']
export const MONITORING_INDUSTRIES = ['Security','IT / Networking','Fire Protection','Low Voltage','Telecom','Audio/Visual','HVAC']

export const _MAINT_BODY = 'This Preventive Maintenance Agreement is between {{companyName}} ("Provider") and {{clientName}} ("Client") for {{proposalName}}.\n\nSERVICES: Provider will perform {{maintenanceCalls}} scheduled maintenance visit(s) per year including inspection, testing, and minor adjustments.\n\nBILLING: Initial fee of ${{initialFee}} billed with project. Recurring service billed at ${{recurringFee}} ({{billingFrequency}}).\n\nLABOR: Additional service calls billed at ${{laborRate}}/hr during standard business hours.\n\nTERM: One (1) year from execution, auto-renewing unless cancelled with 30-days written notice.'
export const _STD_BODY = 'This Service Level Agreement is between {{companyName}} ("Provider") and {{clientName}} ("Client") for {{proposalName}}.\n\nRESPONSE TIME: Provider guarantees a {{responseTime}} response time for all service requests.\n\nBILLING: Services billed {{billingFrequency}} at ${{laborRate}}/hr. Emergency/after-hours calls billed at ${{emergencyRate}}/hr.\n\nTERM: One (1) year from execution, auto-renewing unless cancelled with 30-days written notice.'
export const _PRI_BODY = 'This Priority Service Level Agreement is between {{companyName}} ("Provider") and {{clientName}} ("Client") for {{proposalName}}.\n\nRESPONSE TIME: Provider guarantees a {{responseTime}} priority response for all service requests.\n\nINCLUDED MAINTENANCE: {{maintenanceCalls}} included maintenance visit(s) per year. Recurring fee: ${{recurringFee}} ({{billingFrequency}}).\n\nBILLING: Labor at ${{laborRate}}/hr. Emergency calls at ${{emergencyRate}}/hr.\n\nTERM: One (1) year from execution, auto-renewing unless cancelled with 30-days written notice.'

export const SLA_TIER_DEFAULTS = {
  'Security':           { enabled: true,  tiers: [
    { id: 'maintenance', name: 'Preventive Maintenance',  response_time_hours: null, labor_rate: 110, emergency_rate: null, billing_frequency: 'Annually',  maintenance_calls_per_year: 2, initial_fee: 0, recurring_fee: 199, body: _MAINT_BODY },
    { id: 'standard',   name: 'Standard SLA',             response_time_hours: 4,    labor_rate: 125, emergency_rate: 175,  billing_frequency: 'Quarterly', maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
    { id: 'priority',   name: 'Priority SLA',             response_time_hours: 2,    labor_rate: 125, emergency_rate: 155,  billing_frequency: 'Monthly',   maintenance_calls_per_year: 1, initial_fee: 0, recurring_fee: 349, body: _PRI_BODY },
  ]},
  'Audio/Visual':       { enabled: true,  tiers: [
    { id: 'maintenance', name: 'Preventive Maintenance',  response_time_hours: null, labor_rate: 100, emergency_rate: null, billing_frequency: 'Annually',  maintenance_calls_per_year: 2, initial_fee: 0, recurring_fee: 149, body: _MAINT_BODY },
    { id: 'standard',   name: 'Standard SLA',             response_time_hours: 8,    labor_rate: 115, emergency_rate: 165,  billing_frequency: 'Quarterly', maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
  ]},
  'IT / Networking':    { enabled: true,  tiers: [
    { id: 'maintenance', name: 'Preventive Maintenance',  response_time_hours: null, labor_rate: 120, emergency_rate: null, billing_frequency: 'Monthly',   maintenance_calls_per_year: 4, initial_fee: 0, recurring_fee: 299, body: _MAINT_BODY },
    { id: 'standard',   name: 'Standard SLA',             response_time_hours: 4,    labor_rate: 135, emergency_rate: 195,  billing_frequency: 'Monthly',   maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
    { id: 'priority',   name: 'Priority SLA',             response_time_hours: 2,    labor_rate: 135, emergency_rate: 175,  billing_frequency: 'Monthly',   maintenance_calls_per_year: 2, initial_fee: 0, recurring_fee: 499, body: _PRI_BODY },
  ]},
  'Low Voltage':        { enabled: true,  tiers: [
    { id: 'maintenance', name: 'Preventive Maintenance',  response_time_hours: null, labor_rate: 95,  emergency_rate: null, billing_frequency: 'Annually',  maintenance_calls_per_year: 1, initial_fee: 0, recurring_fee: 149, body: _MAINT_BODY },
    { id: 'standard',   name: 'Standard SLA',             response_time_hours: 8,    labor_rate: 110, emergency_rate: 155,  billing_frequency: 'Quarterly', maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
  ]},
  'Fire Protection':    { enabled: true,  tiers: [
    { id: 'maintenance', name: 'Preventive Maintenance',  response_time_hours: null, labor_rate: 115, emergency_rate: null, billing_frequency: 'Annually',  maintenance_calls_per_year: 2, initial_fee: 0, recurring_fee: 249, body: _MAINT_BODY },
    { id: 'standard',   name: 'Standard SLA',             response_time_hours: 4,    labor_rate: 130, emergency_rate: 185,  billing_frequency: 'Monthly',   maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
    { id: 'priority',   name: 'Priority SLA',             response_time_hours: 2,    labor_rate: 130, emergency_rate: 165,  billing_frequency: 'Monthly',   maintenance_calls_per_year: 2, initial_fee: 0, recurring_fee: 449, body: _PRI_BODY },
  ]},
  'HVAC':               { enabled: true,  tiers: [
    { id: 'maintenance', name: 'Preventive Maintenance',  response_time_hours: null, labor_rate: 105, emergency_rate: null, billing_frequency: 'Annually',  maintenance_calls_per_year: 2, initial_fee: 0, recurring_fee: 199, body: _MAINT_BODY },
    { id: 'standard',   name: 'Standard SLA',             response_time_hours: 24,   labor_rate: 120, emergency_rate: 170,  billing_frequency: 'Quarterly', maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
  ]},
  'Electrical':         { enabled: true,  tiers: [
    { id: 'maintenance', name: 'Preventive Maintenance',  response_time_hours: null, labor_rate: 110, emergency_rate: null, billing_frequency: 'Annually',  maintenance_calls_per_year: 1, initial_fee: 0, recurring_fee: 149, body: _MAINT_BODY },
    { id: 'standard',   name: 'Standard SLA',             response_time_hours: 8,    labor_rate: 125, emergency_rate: 180,  billing_frequency: 'Quarterly', maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
  ]},
  'Telecom':            { enabled: true,  tiers: [
    { id: 'maintenance', name: 'Preventive Maintenance',  response_time_hours: null, labor_rate: 105, emergency_rate: null, billing_frequency: 'Annually',  maintenance_calls_per_year: 2, initial_fee: 0, recurring_fee: 199, body: _MAINT_BODY },
    { id: 'standard',   name: 'Standard SLA',             response_time_hours: 4,    labor_rate: 120, emergency_rate: 170,  billing_frequency: 'Monthly',   maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
    { id: 'priority',   name: 'Priority SLA',             response_time_hours: 2,    labor_rate: 120, emergency_rate: 150,  billing_frequency: 'Monthly',   maintenance_calls_per_year: 1, initial_fee: 0, recurring_fee: 399, body: _PRI_BODY },
  ]},
  'Solar':              { enabled: false, tiers: [
    { id: 'maintenance', name: 'Preventive Maintenance',  response_time_hours: null, labor_rate: 95,  emergency_rate: null, billing_frequency: 'Annually',  maintenance_calls_per_year: 2, initial_fee: 0, recurring_fee: 149, body: _MAINT_BODY },
    { id: 'standard',   name: 'Standard SLA',             response_time_hours: 24,   labor_rate: 110, emergency_rate: 155,  billing_frequency: 'Quarterly', maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
  ]},
  'Mechanical':         { enabled: false, tiers: [
    { id: 'maintenance', name: 'Preventive Maintenance',  response_time_hours: null, labor_rate: 100, emergency_rate: null, billing_frequency: 'Annually',  maintenance_calls_per_year: 2, initial_fee: 0, recurring_fee: 179, body: _MAINT_BODY },
    { id: 'standard',   name: 'Standard SLA',             response_time_hours: 24,   labor_rate: 115, emergency_rate: 165,  billing_frequency: 'Quarterly', maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
  ]},
  'Plumbing':           { enabled: false, tiers: [
    { id: 'standard',   name: 'Standard Service Agreement', response_time_hours: 24,  labor_rate: 110, emergency_rate: 160,  billing_frequency: 'Quarterly', maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
  ]},
  'General Contractor': { enabled: false, tiers: [
    { id: 'standard',   name: 'Standard Service Agreement', response_time_hours: 48,  labor_rate: 105, emergency_rate: 150,  billing_frequency: 'Quarterly', maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
  ]},
  'Other':              { enabled: false, tiers: [
    { id: 'standard',   name: 'Standard Service Agreement', response_time_hours: 24,  labor_rate: 100, emergency_rate: 150,  billing_frequency: 'Quarterly', maintenance_calls_per_year: 0, initial_fee: 0, recurring_fee: 0,   body: _STD_BODY },
  ]},
}

export const MONITORING_DEFAULTS = {
  'Security':        { enabled: true,  name: 'Security Monitoring Contract',   monthly_fee: 49,  monitored_systems: 'Cameras, Access Control, Intrusion Alarm',            billing_frequency: 'Monthly', escalation_contacts: 2, body: 'This Monitoring Contract is between {{companyName}} ("Provider") and {{clientName}} ("Client") for {{proposalName}}.\n\nSERVICES: Provider will provide continuous monitoring of {{monitoredSystems}}.\n\nBILLING: Monitoring services billed at ${{monthlyFee}}/month, invoiced {{billingFrequency}}.\n\nESCALATION: Client shall designate {{escalationContacts}} authorized contact(s) for alerts and dispatch authorization.\n\nTERM: One (1) year from execution, auto-renewing unless cancelled with 30-days written notice.\n\nClient Signature: ___________________________      Date: ___________' },
  'IT / Networking': { enabled: true,  name: 'Network Monitoring Contract',    monthly_fee: 99,  monitored_systems: 'Network Infrastructure, Servers, Endpoints',            billing_frequency: 'Monthly', escalation_contacts: 2, body: 'This Monitoring Contract is between {{companyName}} ("Provider") and {{clientName}} ("Client") for {{proposalName}}.\n\nSERVICES: Provider will provide 24/7 monitoring of {{monitoredSystems}} with proactive alerting for critical events.\n\nBILLING: Monitoring services billed at ${{monthlyFee}}/month, invoiced {{billingFrequency}}.\n\nESCALATION: Client shall designate {{escalationContacts}} authorized contact(s) for alert notification and response.\n\nTERM: One (1) year from execution, auto-renewing unless cancelled with 30-days written notice.\n\nClient Signature: ___________________________      Date: ___________' },
  'Fire Protection': { enabled: true,  name: 'Fire Alarm Monitoring Contract', monthly_fee: 35,  monitored_systems: 'Fire Alarms, Smoke Detectors, Suppression Systems',      billing_frequency: 'Monthly', escalation_contacts: 3, body: 'This Monitoring Contract is between {{companyName}} ("Provider") and {{clientName}} ("Client") for {{proposalName}}.\n\nSERVICES: Provider will provide central station monitoring of {{monitoredSystems}} with immediate dispatch protocols.\n\nBILLING: Monitoring services billed at ${{monthlyFee}}/month, invoiced {{billingFrequency}}.\n\nESCALATION: Client shall designate {{escalationContacts}} authorized contacts for alarm notification and dispatch.\n\nTERM: One (1) year from execution, auto-renewing unless cancelled with 30-days written notice.\n\nClient Signature: ___________________________      Date: ___________' },
  'Low Voltage':     { enabled: true,  name: 'Systems Monitoring Contract',    monthly_fee: 45,  monitored_systems: 'Low Voltage Systems, Access Control, AV Equipment',     billing_frequency: 'Monthly', escalation_contacts: 2, body: 'This Monitoring Contract is between {{companyName}} ("Provider") and {{clientName}} ("Client") for {{proposalName}}.\n\nSERVICES: Provider will provide remote monitoring of {{monitoredSystems}} with proactive issue identification.\n\nBILLING: Monitoring services billed at ${{monthlyFee}}/month, invoiced {{billingFrequency}}.\n\nESCALATION: Client shall designate {{escalationContacts}} authorized contact(s) for notification and dispatch.\n\nTERM: One (1) year from execution, auto-renewing unless cancelled with 30-days written notice.\n\nClient Signature: ___________________________      Date: ___________' },
  'Telecom':         { enabled: true,  name: 'Telecom Monitoring Contract',    monthly_fee: 75,  monitored_systems: 'Voice Systems, Data Infrastructure, Network Equipment', billing_frequency: 'Monthly', escalation_contacts: 2, body: 'This Monitoring Contract is between {{companyName}} ("Provider") and {{clientName}} ("Client") for {{proposalName}}.\n\nSERVICES: Provider will provide continuous monitoring of {{monitoredSystems}} with alerting for outages and performance degradation.\n\nBILLING: Monitoring services billed at ${{monthlyFee}}/month, invoiced {{billingFrequency}}.\n\nESCALATION: Client shall designate {{escalationContacts}} authorized contact(s) for notification.\n\nTERM: One (1) year from execution, auto-renewing unless cancelled with 30-days written notice.\n\nClient Signature: ___________________________      Date: ___________' },
  'Audio/Visual':    { enabled: false, name: 'AV Systems Monitoring',          monthly_fee: 39,  monitored_systems: 'AV Systems, Displays, Control Systems',                  billing_frequency: 'Monthly', escalation_contacts: 1, body: 'This Monitoring Contract is between {{companyName}} ("Provider") and {{clientName}} ("Client") for {{proposalName}}.\n\nSERVICES: Provider will provide remote monitoring of {{monitoredSystems}} with proactive alerts for system failures.\n\nBILLING: Monitoring services billed at ${{monthlyFee}}/month, invoiced {{billingFrequency}}.\n\nESCALATION: Client shall designate {{escalationContacts}} authorized contact(s) for notification.\n\nTERM: One (1) year from execution, auto-renewing unless cancelled with 30-days written notice.\n\nClient Signature: ___________________________      Date: ___________' },
  'HVAC':            { enabled: false, name: 'HVAC Monitoring Contract',       monthly_fee: 59,  monitored_systems: 'HVAC Units, Thermostats, Air Quality Sensors',           billing_frequency: 'Monthly', escalation_contacts: 1, body: 'This Monitoring Contract is between {{companyName}} ("Provider") and {{clientName}} ("Client") for {{proposalName}}.\n\nSERVICES: Provider will provide remote monitoring of {{monitoredSystems}} with alerts for performance issues.\n\nBILLING: Monitoring services billed at ${{monthlyFee}}/month, invoiced {{billingFrequency}}.\n\nESCALATION: Client shall designate {{escalationContacts}} authorized contact(s) for notification.\n\nTERM: One (1) year from execution, auto-renewing unless cancelled with 30-days written notice.\n\nClient Signature: ___________________________      Date: ___________' },
}
